name: Generate Contribution Snake
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # nightly UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./scripts

      - name: Generate snake SVG
        env:
          GH_USERNAME: REDX-CORPORATION
          SNAKE_COLOR: "#FF0000"
        run: node generate-snake.js
        working-directory: ./scripts

      - name: Commit generated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update contribution snake"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
